services:
  postgres:
    image: postgres:17.5-alpine
    container_name: club-db
    environment:
      POSTGRES_DB: clubdames
      POSTGRES_USER: clubuser
      POSTGRES_PASSWORD: clubpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - club-net

  api:
    build:
      context: ./api
    container_name: club-api
    depends_on:
      - postgres
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clubdames
      SPRING_DATASOURCE_USERNAME: clubuser
      SPRING_DATASOURCE_PASSWORD: clubpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - club-net

  bo:
    build:
      context: ./bo
      dockerfile: Dockerfile.dev
    container_name: club-bo
    ports:
      - "3000-3010:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - PORT=3000
    command: npm run dev
    networks:
      - club-net
    develop:
      watch:
        - action: sync
          path: ./bo
          target: /usr/src/app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./bo/package.json

volumes:
  pgdata:


networks:
  club-net:
